FROM ros:jazzy

RUN apt update && \
apt-get upgrade -y && \
apt-get install -y \
ros-jazzy-ros2-control \
ros-jazzy-ros2-controllers \
ros-jazzy-controller-manager \
ros-jazzy-moveit \
ros-jazzy-moveit-py